# Generated by Django 6.0 on 2026-01-31 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('acc_num', models.AutoField(default=1234567890, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('aadhar', models.PositiveBigIntegerField(unique=True)),
                ('pan', models.CharField(max_length=10, unique=True)),
                ('phone', models.PositiveBigIntegerField(unique=10)),
                ('pin', models.CharField(max_length=64)),
                ('bal', models.IntegerField(default=1000)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
            ],
        ),
    ]
